version: "3.9"

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  webserver:
    image: app
    restart: always
    command: python manage.py runserver 0.0.0.0:3000
    volumes:
      - .:/code
    ports:
      - "3000:3000"
    links:
      - mongodb
    depends_on:
      - migration

  migration:
    build: .
    image: app
    command: python manage.py migrate
    volumes:
      - .:/code
    links:
      - mongodb