version: '3.1'

volumes:
  db:

services:
  mongodb:
    image: mongo
    restart: always
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongoadmin
      MONGO_INITDB_DATABASE: pro
    ports:
      - 27017:27018

  web:
    image: app
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/product
    ports:
      - 8000:8006
    links:
      - mongodb
    depends_on:
      - migration

  migration:
    build: .
    image: app
    command: python manage.py migrate
    volumes:
      - .:/product
    links:
      - mongodb
    depends_on:
      - make_migrations

  make_migrations:
    build: .
    image: app
    command: python manage.py makemigrations
    volumes:
      - .:/django_mongodb_docker
    links:
      - mongodb
    depends_on:
      - mongodb