# Generated by Django 3.1.12 on 2023-06-23 22:28

from django.db import migrations, models
import djongo.models.fields
import productApi.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ownerName', models.CharField(max_length=100)),
                ('masterName', models.CharField(max_length=100)),
                ('startDate', models.DateField()),
                ('developers', djongo.models.fields.ArrayField(model_container=productApi.models.Developer)),
                ('methodology', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
