# Generated by Django 3.1.12 on 2023-06-27 18:30

from django.db import migrations, models
import djongo.models.fields
import productApi.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('ownerName', models.CharField(max_length=500)),
                ('masterName', models.CharField(max_length=500)),
                ('startDate', models.DateField()),
                ('developers', djongo.models.fields.ArrayField(model_container=productApi.models.Developer)),
                ('methodology', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=500)),
            ],
        ),
    ]
